name: flutter_chat_demo
description: This is the demo for chat app by Flutter

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.5
  firebase_core: 1.21.1
  firebase_auth: 3.7.0
  google_sign_in: 5.4.1
  cloud_firestore:  3.4.6
  fluttertoast: 8.0.9
  image_picker: 0.8.5+3
  shared_preferences: 2.0.15
  firebase_storage: 10.3.7
  firebase_messaging: 13.0.0
  flutter_local_notifications: 9.8.0+1
  photo_view: 0.14.0
  provider: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - images/

environment:
  sdk: ">=2.17.6 <3.0.0"