name: flutter_chat_demo
description: This is the demo for chat app by Flutter
publish_to: 'none'

version: 1.0.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  google_sign_in: ^6.1.0
  cloud_firestore: ^4.5.0
  fluttertoast: ^8.2.1
  image_picker: ^1.0.4
  shared_preferences: ^2.1.0
  firebase_storage: ^11.1.0
  firebase_messaging: ^14.4.0
  flutter_local_notifications: ^16.1.0
  photo_view: 0.14.0
  provider: ^6.0.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true

  assets:
    - images/

environment:
  sdk: ">=2.17.6 <3.0.0"